train : 
  plot :
    dgda56qz:
      slurm_id: 0
      description: "Latent alignment loss (ramp up) + cosine loss (lr constant)  "
      eval: vgbndhco
    q3t4hzw6:
      slurm_id: 0
      description: "Latent alignment loss + cosine loss (lr constant)"
      eval: vgbndhco
    hn3v2uk6:
      slurm_id: 0
      description: "cosine loss (lr constant) "
      eval: vgbndhco
