train:
  plot:
    b95dmhtw:
      slurm_id: 0
      description: "ERA5"
      eval: vgbndhco 
    pppcna9q:
      slurm_id: 0
      description: "EERIE"
      eval: vgbndhco
    i9eqk382: 
      slurm_id: 0
      description: "EERIE_after_fix"
      eval: vgbndhco
