train : 
  plot :
    iiw09hvy:
      slurm_id: 0
      description: "Geom enforce"
      eval: vgbndhco
    hn3v2uk6:
      slurm_id: 0
      description: "cosine loss (lr constant) "
      eval: vgbndhco
