train : 
  plot :
    hn3v2uk6:
      slurm_id: 0
      description: "cosine loss (lr constant) "
      eval: vgbndhco
    iiw09hvy:
      slurm_id: 0
      description: "Geom enforce"
      eval: vgbndhco
    hh1gz328:
      slurm_id: 0
      description: "Geom enforce (Muon Optimizer)"
      eval: vgbndhco
    hvqa3x2g:
      slurm_id: 0
      description: "Geom enforce (Muon Optimizer) + target_encoding(fourier)"
      eval: vgbndhco
    ny4brf5u:
      slurm_id: 0
      description: "Geom enforce (Muon Optimizer) + target_encoding(fourier) + Swiglu emebdding"
      eval: vgbndhco
